Repository opencv/opencv_contrib, pull requests merged in 2022-07, with the labels that each got.

#3292 Fix file ending
  modules/aruco/tutorials/aruco_board_detection/aruco_board_detection.markdown
  modules/aruco/tutorials/aruco_board_detection/images/board.png
  modules/aruco/tutorials/charuco_detection/charuco_detection.markdown
  modules/aruco/tutorials/charuco_detection/images/charucoboard.png
  modules/bioinspired/tutorials/retina_illusion/images/checkershadow_illusion4med_proof.png
  modules/bioinspired/tutorials/retina_illusion/retina_illusion.markdown
Labels: bug, category: documentation

#3298 suppress warning on GCC 7 and later
  modules/aruco/CMakeLists.txt
  modules/ccalib/CMakeLists.txt
  modules/datasets/CMakeLists.txt
  modules/dnn_objdetect/CMakeLists.txt
  modules/dpm/CMakeLists.txt
  modules/face/CMakeLists.txt
  modules/line_descriptor/CMakeLists.txt
  modules/optflow/CMakeLists.txt
  modules/rgbd/CMakeLists.txt
  modules/text/CMakeLists.txt
  modules/tracking/CMakeLists.txt
  modules/xfeatures2d/CMakeLists.txt
  modules/ximgproc/CMakeLists.txt
  modules/xobjdetect/CMakeLists.txt
  modules/xphoto/CMakeLists.txt
Labels: category: build/install

#3306 ximgproc: fix mismatched new delete
  modules/ximgproc/src/edge_drawing.cpp
Labels: bug, category: ximgproc
